
CREATE TABLE "USER_TOKEN" 
   (	"DELEGATE_ID" VARCHAR2(50 BYTE), 
	"TOKEN" VARCHAR2(50 BYTE), 
	"CREATE_DATE" TIMESTAMP (6), 
	"EXPIRY_DATE" TIMESTAMP (6)
   );
   
   CREATE TABLE "ERROR_CODE" 
   (	"ID" NUMBER(19,0), 
"ACTIVE" NUMBER(1,0), 
"ERROR_CODE" VARCHAR2(255 CHAR), 
"ERROR_NAME_ARABIC" VARCHAR2(255 CHAR), 
"ERROR_NAME_ENGLISH" VARCHAR2(255 CHAR)
   )

ALTER TABLE TM_PROJECTS ADD (QR_CODE VARCHAR2(50));

ALTER TABLE TM_RECEIPT_DETAILS ADD (CREATED_BY_TEMP VARCHAR2(50));
UPDATE TM_RECEIPT_DETAILS SET CREATED_BY_TEMP = CREATED_BY;
ALTER TABLE TM_RECEIPT_DETAILS DROP COLUMN CREATED_BY;
ALTER TABLE TM_RECEIPT_DETAILS RENAME COLUMN CREATED_BY_TEMP TO CREATED_BY;   


ALTER TABLE TM_RECEIPT_PAYMENTS ADD (CREATEDBY_TEMP VARCHAR2(50));
UPDATE TM_RECEIPT_PAYMENTS SET CREATEDBY_TEMP = CREATEDBY;
ALTER TABLE TM_RECEIPT_PAYMENTS DROP COLUMN CREATEDBY;
ALTER TABLE TM_RECEIPT_PAYMENTS RENAME COLUMN CREATEDBY_TEMP TO CREATEDBY; 


ALTER TABLE TM_RECEIPTS ADD (CREATED_BY_TEMP VARCHAR2(50));
UPDATE TM_RECEIPTS SET CREATED_BY_TEMP = CREATED_BY;
ALTER TABLE TM_RECEIPTS DROP COLUMN CREATED_BY;
ALTER TABLE TM_RECEIPTS RENAME COLUMN CREATED_BY_TEMP TO CREATED_BY; 


ALTER TABLE TM_RECEIPTS ADD (TM_DELEGATES_CODE_TEMP VARCHAR2(50));
UPDATE TM_RECEIPTS SET TM_DELEGATES_CODE_TEMP = TM_DELEGATES_CODE;
ALTER TABLE TM_RECEIPTS DROP COLUMN TM_DELEGATES_CODE;
ALTER TABLE TM_RECEIPTS RENAME COLUMN TM_DELEGATES_CODE_TEMP TO TM_DELEGATES_CODE; 


ALTER TABLE TM_RECEIPTS ADD CONSTRAINT RECEIPT_ID_UNIQUE UNIQUE (RECEIPT_CODE);
ALTER TABLE TM_RECEIPT_DETAILS ADD CONSTRAINT RECEIPT_DETAIL_ID_UNIQUE UNIQUE (RECEIPT_DETAIL_CODE);
ALTER TABLE TM_RECEIPT_PAYMENTS ADD CONSTRAINT PAYMENT_ID_UNIQUE UNIQUE (PAYMENT_CODE);
ALTER TABLE TM_RECEIPT_PAYMENTS ADD CONSTRAINT PAYMENT_RECEIPT_ID_UNIQUE UNIQUE (RECEIPT_CODE);


SELECT MAX(RECEIPT_CODE) + 1 from TM_RECEIPTS;
CREATE SEQUENCE tm_receipts_seq INCREMENT BY 1 START WITH 100000000000128844 MAXVALUE 99999999999999999999999999999 MINVALUE 1 NOCACHE;

SELECT MAX(RECEIPT_DETAIL_CODE) + 1 from TM_RECEIPT_DETAILS;
CREATE SEQUENCE tm_receipt_details_seq INCREMENT BY 1 START WITH 100000000000203846 MAXVALUE 99999999999999999999999999999 MINVALUE 1 NOCACHE;

SELECT MAX(PAYMENT_CODE) + 1 from TM_RECEIPT_PAYMENTS;
CREATE SEQUENCE tm_receipt_payments_seq INCREMENT BY 1 START WITH 100000000000129621 MAXVALUE 99999999999999999999999999999 MINVALUE 1 NOCACHE;