ALTER TABLE CP_FINANCIERS_BENEFICIANT ADD (COUNTRY_CODE_TEMP NUMBER);
UPDATE CP_FINANCIERS_BENEFICIANT SET COUNTRY_CODE_TEMP = COUNTRY_CODE;
ALTER TABLE CP_FINANCIERS_BENEFICIANT DROP COLUMN COUNTRY_CODE;
ALTER TABLE CP_FINANCIERS_BENEFICIANT RENAME COLUMN COUNTRY_CODE_TEMP TO COUNTRY_CODE;



/* disable trigger SP_BMCASES_UPDATE_TRG before this change */
ALTER TABLE SP_CASES ADD (GENDER_TEMP varchar(100));
update SP_CASES set GENDER_TEMP= GENDER;
ALTER TABLE SP_CASES DROP COLUMN GENDER;
ALTER TABLE SP_CASES RENAME COLUMN GENDER_TEMP TO GENDER;

ALTER TABLE SP_CASES ADD (CHECK_FLAG NUMBER(1,0));
update SP_CASES set CHECK_FLAG=0;

ALTER TABLE SP_CASES ADD (HAI_OFFICE_TEMP varchar(50));
update SP_CASES set HAI_OFFICE_TEMP= HAI_OFFICE;
ALTER TABLE SP_CASES DROP COLUMN HAI_OFFICE;
ALTER TABLE SP_CASES RENAME COLUMN HAI_OFFICE_TEMP TO HAI_OFFICE;

ALTER TABLE SP_CASES ADD (NATIONALITYID_TEMP varchar(50));
update SP_CASES set NATIONALITYID_TEMP= NATIONALITYID;
ALTER TABLE SP_CASES DROP COLUMN NATIONALITYID;
ALTER TABLE SP_CASES RENAME COLUMN NATIONALITYID_TEMP TO NATIONALITYID;

ALTER TABLE SP_CASES ADD (SPONCER_CATEGORY_TEMP varchar(50));
update SP_CASES set SPONCER_CATEGORY_TEMP= SPONCER_CATEGORY;
ALTER TABLE SP_CASES DROP COLUMN SPONCER_CATEGORY;
ALTER TABLE SP_CASES RENAME COLUMN SPONCER_CATEGORY_TEMP TO SPONCER_CATEGORY;

ALTER TABLE SP_CONTRACTS_CASES ADD (FIRST_TITLE varchar(100));

ALTER TABLE TM_DELEGATES ADD (DELEGATE_ID_TEMP NUMBER);
UPDATE TM_DELEGATES SET DELEGATE_ID_TEMP = DELEGATE_ID;
ALTER TABLE TM_DELEGATES DROP COLUMN DELEGATE_ID;
ALTER TABLE TM_DELEGATES RENAME COLUMN DELEGATE_ID_TEMP TO DELEGATE_ID;

ALTER TABLE TM_DELEGATES ADD (STATUS_TEMP NUMBER(1,0));
UPDATE TM_DELEGATES SET STATUS_TEMP = STATUS;
ALTER TABLE TM_DELEGATES DROP COLUMN STATUS;
ALTER TABLE TM_DELEGATES RENAME COLUMN STATUS_TEMP TO STATUS;

ALTER TABLE TM_DELEGATES ADD (ADMIN_USER NUMBER(1,0));

ALTER TABLE TM_DELEGATES ADD (MAX_LIMIT_TEMP NUMBER(1,0));
UPDATE TM_DELEGATES SET MAX_LIMIT_TEMP = MAX_LIMIT;
ALTER TABLE TM_DELEGATES DROP COLUMN MAX_LIMIT;
ALTER TABLE TM_DELEGATES RENAME COLUMN MAX_LIMIT_TEMP TO MAX_LIMIT;

ALTER TABLE TM_PROJECTS ADD (PROJECT_STATUS_TEMP NUMBER(1,0));
ALTER TABLE TM_PROJECTS DROP COLUMN PROJECT_STATUS;
ALTER TABLE TM_PROJECTS RENAME COLUMN PROJECT_STATUS_TEMP TO PROJECT_STATUS;
update TM_PROJECTS set PROJECT_STATUS= 1;

ALTER TABLE TM_PROJECTS ADD (QR_CODE varchar(100));

ALTER TABLE TM_RECEIPT_PAYMENTS ADD (DEDUCTION_NUMBER VARCHAR2(30 BYTE));
ALTER TABLE TM_RECEIPT_PAYMENTS ADD (ACCOUNT_NUMBER nvarchar2(1000));
ALTER TABLE TM_RECEIPT_PAYMENTS ADD (ACCOUNT_NAME nvarchar2(1000));
ALTER TABLE TM_RECEIPT_PAYMENTS ADD (BANK_CODE NVARCHAR2(100));

ALTER TABLE TM_RECEIPTS ADD (RECEIPT_TYPE VARCHAR2(20));
ALTER TABLE TM_RECEIPT_PAYMENTS ADD (AMOUNT NUMBER);

CREATE SEQUENCE tm_receipts_seq INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 NOCACHE;
CREATE SEQUENCE tm_receipt_details_seq INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 NOCACHE;
CREATE SEQUENCE tm_receipt_payments_seq INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 NOCACHE;

ALTER TABLE AR_RECEIPT_TYPES ADD (RCT_TYPE_IMAGE BLOB);
update TM_DELEGATES set ADMIN_USER=0;
update TM_PROJECTS set MIN_AMOUNT=0;
update tm_delegates set EXPIRY_DATE = (TO_DATE('2020/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));


ALTER TABLE FND_LOOKUP_VALUES ADD (LOOKUP_IMAGE BLOB);
ALTER TABLE PROJECT_TYPES ADD (PROJECT_IMAGE BLOB);

ALTER TABLE SCPROJECT_TYPES_INFO ADD (COUNTRY_ID_TEMP varchar(50));
update SCPROJECT_TYPES_INFO set COUNTRY_ID_TEMP= COUNTRY_ID;
ALTER TABLE SCPROJECT_TYPES_INFO DROP COLUMN COUNTRY_ID;
ALTER TABLE SCPROJECT_TYPES_INFO RENAME COLUMN COUNTRY_ID_TEMP TO COUNTRY_ID;

ALTER TABLE SC_PROJECT ADD (PROJECT_TYPE_TEMP NUMBER);
UPDATE SC_PROJECT SET PROJECT_TYPE_TEMP = PROJECT_TYPE;
ALTER TABLE SC_PROJECT DROP COLUMN PROJECT_TYPE;
ALTER TABLE SC_PROJECT RENAME COLUMN PROJECT_TYPE_TEMP TO PROJECT_TYPE;

ALTER TABLE SC_PROJECT ADD (COUNTRY_ID_TEMP varchar(50));
UPDATE SC_PROJECT SET COUNTRY_ID_TEMP = COUNTRY_ID;
ALTER TABLE SC_PROJECT DROP COLUMN COUNTRY_ID;
ALTER TABLE SC_PROJECT RENAME COLUMN COUNTRY_ID_TEMP TO COUNTRY_ID;

ALTER TABLE SC_PROJECT ADD (DONOR_TEMP NUMBER);
UPDATE SC_PROJECT SET DONOR_TEMP = DONOR;
ALTER TABLE SC_PROJECT DROP COLUMN DONOR;
ALTER TABLE SC_PROJECT RENAME COLUMN DONOR_TEMP TO DONOR;

ALTER TABLE TM_RECEIPT_DETAILS MODIFY( DONATOR_COUNTRY_ID varchar(50));
ALTER TABLE TM_RECEIPT_DETAILS MODIFY( PROJECT_COUNTRY_ID varchar(50));



Insert into FND_LOOKUP_VALUES (LOOKUP_TYPE,LOOKUP_CODE,VALUE,YES_NO,ARABIC_VALUE,ADDED_VALUES,SER_NO) values ('PARTICULARGENDER','1','Male',1,'ذكر',null,null);
Insert into FND_LOOKUP_VALUES (LOOKUP_TYPE,LOOKUP_CODE,VALUE,YES_NO,ARABIC_VALUE,ADDED_VALUES,SER_NO) values ('PARTICULARGENDER','2','Female',1,'أنثى',null,null);
Insert into FND_LOOKUP_VALUES (LOOKUP_TYPE,LOOKUP_CODE,VALUE,YES_NO,ARABIC_VALUE,ADDED_VALUES,SER_NO) values ('PARTICULARGENDER','3','UnSpecified',1,'غير محدد',null,null);

Insert into FND_LOOKUP_VALUES (LOOKUP_TYPE,LOOKUP_CODE,VALUE,YES_NO,ARABIC_VALUE,ADDED_VALUES,SER_NO) values ('SP_GIFT_DESC','2','عيدية الأضحى',1,'عيدية الأضحى',null,null);
Insert into FND_LOOKUP_VALUES (LOOKUP_TYPE,LOOKUP_CODE,VALUE,YES_NO,ARABIC_VALUE,ADDED_VALUES,SER_NO) values ('SP_GIFT_DESC','7','صيانه منزل',1,'صيانه منزل',null,null);
Insert into FND_LOOKUP_VALUES (LOOKUP_TYPE,LOOKUP_CODE,VALUE,YES_NO,ARABIC_VALUE,ADDED_VALUES,SER_NO) values ('SP_GIFT_DESC','12','ايجار منزل',1,'ايجار منزل',null,null);
Insert into FND_LOOKUP_VALUES (LOOKUP_TYPE,LOOKUP_CODE,VALUE,YES_NO,ARABIC_VALUE,ADDED_VALUES,SER_NO) values ('SP_GIFT_DESC','13','هدايا',1,'هدايا',null,null);
Insert into FND_LOOKUP_VALUES (LOOKUP_TYPE,LOOKUP_CODE,VALUE,YES_NO,ARABIC_VALUE,ADDED_VALUES,SER_NO) values ('SP_GIFT_DESC','14','أضحية يتيم',1,'أضحية يتيم',null,null);
Insert into FND_LOOKUP_VALUES (LOOKUP_TYPE,LOOKUP_CODE,VALUE,YES_NO,ARABIC_VALUE,ADDED_VALUES,SER_NO) values ('SP_GIFT_DESC','11','قروض انتاجية',1,'قروض انتاجية',null,null);
Insert into FND_LOOKUP_VALUES (LOOKUP_TYPE,LOOKUP_CODE,VALUE,YES_NO,ARABIC_VALUE,ADDED_VALUES,SER_NO) values ('SP_GIFT_DESC','1','كسوة عيد',1,'كسوة عيد',null,null);
Insert into FND_LOOKUP_VALUES (LOOKUP_TYPE,LOOKUP_CODE,VALUE,YES_NO,ARABIC_VALUE,ADDED_VALUES,SER_NO) values ('SP_GIFT_DESC','3','عيدية الفطر',1,'عيدية الفطر',null,null);
Insert into FND_LOOKUP_VALUES (LOOKUP_TYPE,LOOKUP_CODE,VALUE,YES_NO,ARABIC_VALUE,ADDED_VALUES,SER_NO) values ('SP_GIFT_DESC','4','مبلغ ضافي',1,'مبلغ ضافي',null,null);
Insert into FND_LOOKUP_VALUES (LOOKUP_TYPE,LOOKUP_CODE,VALUE,YES_NO,ARABIC_VALUE,ADDED_VALUES,SER_NO) values ('SP_GIFT_DESC','5','إغاثة عاجلة',1,'إغاثة عاجلة',null,null);
Insert into FND_LOOKUP_VALUES (LOOKUP_TYPE,LOOKUP_CODE,VALUE,YES_NO,ARABIC_VALUE,ADDED_VALUES,SER_NO) values ('SP_GIFT_DESC','6','حقيبة مدرسية',1,'حقيبة مدرسية',null,null);
Insert into FND_LOOKUP_VALUES (LOOKUP_TYPE,LOOKUP_CODE,VALUE,YES_NO,ARABIC_VALUE,ADDED_VALUES,SER_NO) values ('SP_GIFT_DESC','8','علاج',1,'علاج',null,null);
Insert into FND_LOOKUP_VALUES (LOOKUP_TYPE,LOOKUP_CODE,VALUE,YES_NO,ARABIC_VALUE,ADDED_VALUES,SER_NO) values ('SP_GIFT_DESC','9','طرد غذائي',1,'طرد غذائي',null,null);
Insert into FND_LOOKUP_VALUES (LOOKUP_TYPE,LOOKUP_CODE,VALUE,YES_NO,ARABIC_VALUE,ADDED_VALUES,SER_NO) values ('SP_GIFT_DESC','10','أجهزة كهربائية وأثاث منزلي',1,'أجهزة كهربائية وأثاث منزلي',null,null);

-------------------------

ALTER TABLE TM_DELEGATES ADD (PIN_CODE varchar(10));
UPDATE TM_DELEGATES SET PIN_CODE = '0000';

ALTER TABLE TM_DELEGATES ADD (DELEGATE_CATEGORY NUMBER(1,0) DEFAULT(1));

CREATE TABLE TM_DELEGATES_SUPERVISORS
( DELEGATE_ID NUMBER NOT NULL,
  SUPERVISOR_ID NUMBER NOT NULL
);

CREATE SEQUENCE TM_DELEGATES_ATTENDANCE_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999 MINVALUE 1 NOCACHE

CREATE TABLE TM_DELEGATES_ATTENDANCE
( 
  ID NUMBER NOT NULL,
  DELEGATE_ID NUMBER NOT NULL,
  TRANSACTION_TYPE varchar(50) NOT NULL,
  TRANSACTION_DATE DATE NOT NULL,
  LOCATION_LATITUDE FLOAT NULL,
  LOCATION_LONGITUDE FLOAT NULL
);