ALTER TABLE TM_CHARITY_BOX_TRANSFERS_DTL ADD (STATUS VARCHAR2(5));
ALTER TABLE TM_CHARITY_BOX_TRANSFERS_DTL ADD (SUPERVISOR_ID VARCHAR2(100));
ALTER TABLE TM_CHARITY_BOX_TRANSFERS_DTL ADD (TRANSACTION_NUMBER NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL);
ALTER TABLE TM_CHARITY_BOX_TRANSFERS_DTL ADD CONSTRAINT TRANSACTION_NUMBER_UNIQUE UNIQUE (TRANSACTION_NUMBER);
ALTER TABLE TM_CHARITY_BOX_TRANSFERS_DTL ADD CONSTRAINT TRANSFER_LINE_ID_UNIQUE UNIQUE (TRANSFER_LINE_ID);
----------------------------
  CREATE TABLE "TM_DELEGATE_ROUTE" 
   (	"ROUTE_ID" NUMBER, 
	"ROUTE_DATE" DATE, 
	"ROUTE_NUMBER" VARCHAR2(50 BYTE), 
	"DELEGATE_ID" NUMBER, 
	"STATUS" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_BY" NUMBER, 
	"LAST_UPDATED_DATE" DATE, 
	"ORG_ID" NUMBER
   );
   
  CREATE TABLE "TM_DELEGATE_ROUTE_DTL" 
   (	"ROUTE_LINE_ID" NUMBER, 
	"ROUTE_ID" NUMBER, 
	"SUB_LOCATION_ID" NUMBER, 
	"STATUS" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_BY" NUMBER, 
	"LAST_UPDATED_DATE" DATE, 
	"ORG_ID" NUMBER, 
	"CHECKED" NUMBER
   ); 
----------------------------
ALTER TABLE TM_SUB_LOCATIONS ADD (LOCATION_LATITUDE FLOAT);
ALTER TABLE TM_SUB_LOCATIONS ADD (LOCATION_LONGITUDE FLOAT);
----------------------------
ALTER TABLE TM_CHARITY_BOXES ADD (CHARITY_BOX_TYPE_TEMP NUMBER);
UPDATE TM_CHARITY_BOXES SET CHARITY_BOX_TYPE_TEMP = CHARITY_BOX_TYPE;
ALTER TABLE TM_CHARITY_BOXES DROP COLUMN CHARITY_BOX_TYPE;
ALTER TABLE TM_CHARITY_BOXES RENAME COLUMN CHARITY_BOX_TYPE_TEMP TO CHARITY_BOX_TYPE;


ALTER TABLE TM_CHARITY_BOXES ADD (CATEGORY_OF_BOXES_TEMP VARCHAR2(10));
UPDATE TM_CHARITY_BOXES SET CATEGORY_OF_BOXES_TEMP = CATEGORY_OF_BOXES;
ALTER TABLE TM_CHARITY_BOXES DROP COLUMN CATEGORY_OF_BOXES;
ALTER TABLE TM_CHARITY_BOXES RENAME COLUMN CATEGORY_OF_BOXES_TEMP TO CATEGORY_OF_BOXES;


ALTER TABLE TM_CHARITY_BOXES ADD (SUPERVISOR_ID_TEMP VARCHAR2(100));
UPDATE TM_CHARITY_BOXES SET SUPERVISOR_ID_TEMP = SUPERVISOR_ID;
ALTER TABLE TM_CHARITY_BOXES DROP COLUMN SUPERVISOR_ID;
ALTER TABLE TM_CHARITY_BOXES RENAME COLUMN SUPERVISOR_ID_TEMP TO SUPERVISOR_ID;
----------------------------------
ALTER TABLE TM_CHARITY_BOX_TRANSFERS ADD (SUPERVISOR_ID_TEMP VARCHAR2(100));
UPDATE TM_CHARITY_BOX_TRANSFERS SET SUPERVISOR_ID_TEMP = SUPERVISOR_ID;
ALTER TABLE TM_CHARITY_BOX_TRANSFERS DROP COLUMN SUPERVISOR_ID;
ALTER TABLE TM_CHARITY_BOX_TRANSFERS RENAME COLUMN SUPERVISOR_ID_TEMP TO SUPERVISOR_ID;

ALTER TABLE TM_CHARITY_BOX_TRANSFERS ADD (CREATED_BY_TEMP VARCHAR2(100));
UPDATE TM_CHARITY_BOX_TRANSFERS SET CREATED_BY_TEMP = CREATED_BY;
ALTER TABLE TM_CHARITY_BOX_TRANSFERS DROP COLUMN CREATED_BY;
ALTER TABLE TM_CHARITY_BOX_TRANSFERS RENAME COLUMN CREATED_BY_TEMP TO CREATED_BY;
-----------------------------------
ALTER TABLE TM_CHARITY_BOX_TRANSFERS_DTL ADD (CREATED_BY_TEMP VARCHAR2(100));
UPDATE TM_CHARITY_BOX_TRANSFERS_DTL SET CREATED_BY_TEMP = CREATED_BY;
ALTER TABLE TM_CHARITY_BOX_TRANSFERS_DTL DROP COLUMN CREATED_BY;
ALTER TABLE TM_CHARITY_BOX_TRANSFERS_DTL RENAME COLUMN CREATED_BY_TEMP TO CREATED_BY;

ALTER TABLE TM_CHARITY_BOX_TRANSFERS_DTL ADD (ACTION_TYPE_TEMP VARCHAR2(10));
UPDATE TM_CHARITY_BOX_TRANSFERS_DTL SET ACTION_TYPE_TEMP = ACTION_TYPE;
ALTER TABLE TM_CHARITY_BOX_TRANSFERS_DTL DROP COLUMN ACTION_TYPE;
ALTER TABLE TM_CHARITY_BOX_TRANSFERS_DTL RENAME COLUMN ACTION_TYPE_TEMP TO ACTION_TYPE;