
-------------------------------------------------------

ALTER TABLE TM_CHARITY_BOXES ADD (CHARITY_BOX_TYPE_TEMP NUMBER);
UPDATE TM_CHARITY_BOXES SET CHARITY_BOX_TYPE_TEMP = CHARITY_BOX_TYPE;
ALTER TABLE TM_CHARITY_BOXES DROP COLUMN CHARITY_BOX_TYPE;
ALTER TABLE TM_CHARITY_BOXES RENAME COLUMN CHARITY_BOX_TYPE_TEMP TO CHARITY_BOX_TYPE;

-------------------------------------

ALTER TABLE TM_CHARITY_BOXES ADD (CATEGORY_OF_BOXES_TEMP VARCHAR2(10));
UPDATE TM_CHARITY_BOXES SET CATEGORY_OF_BOXES_TEMP = CATEGORY_OF_BOXES;
ALTER TABLE TM_CHARITY_BOXES DROP COLUMN CATEGORY_OF_BOXES;
ALTER TABLE TM_CHARITY_BOXES RENAME COLUMN CATEGORY_OF_BOXES_TEMP TO CATEGORY_OF_BOXES;
-----------------------------------
ALTER TABLE TM_CHARITY_BOX_TRANSFERS_DTL ADD (ACTION_TYPE_TEMP VARCHAR2(10));
UPDATE TM_CHARITY_BOX_TRANSFERS_DTL SET ACTION_TYPE_TEMP = ACTION_TYPE;
ALTER TABLE TM_CHARITY_BOX_TRANSFERS_DTL DROP COLUMN ACTION_TYPE;
ALTER TABLE TM_CHARITY_BOX_TRANSFERS_DTL RENAME COLUMN ACTION_TYPE_TEMP TO ACTION_TYPE;
-----------------------------------

CREATE SEQUENCE CH_BOX_TRANS_SEQ INCREMENT BY 1 START WITH 4624 MAXVALUE 99999999999999999999999999999999999 MINVALUE 1 NOCACHE;
CREATE SEQUENCE CH_BOX_TRANS_DTL_SEQ INCREMENT BY 1 START WITH 7141 MAXVALUE 99999999999999999999999999999999999 MINVALUE 1 NOCACHE;
CREATE SEQUENCE SUB_LOCATION_SEQ INCREMENT BY 1 START WITH 7023 MAXVALUE 99999999999999999999999999999999999 MINVALUE 1 NOCACHE;
CREATE SEQUENCE LOCATION_SEQ INCREMENT BY 1 START WITH 4501 MAXVALUE 99999999999999999999999999999999999 MINVALUE 1 NOCACHE;

----------------------------
ALTER TABLE TM_RECEIPTS ADD CONSTRAINT RECEIPT_NUMBER_UNIQUE UNIQUE (RECEIPT_NUMBER);
----------------------
