Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (4,1,'INVALID_PAYMENT_TYPE','طريقة الدفع المختارة غير موجودة','Selected payment type doesn''t exist');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (5,1,'DELEGATE_NOT_EXIST','المفوض غير موجود','Delegate doesn''t exist');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (6,1,'RECEIPT_DETAILS_REQUIRED','يجب اختيار كوبون او مشروع او كفالة','You must select a coupon or project or sponsorship');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (7,1,'COUPON_TYPE_NOT_EXIST','الكوبون غير موجود','Coupon doesn''t exist');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (8,1,'COUPON_AMOUNT_LESS_MINIMUM','مبلغ التبرع اقل من المبلغ المسموح به للكوبون','Amount is less than coupon minimum amount');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (9,1,'DONATOR_NAME_REQUIRED','يجب ادخال اسم المتبرع','Please enter donator name');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (10,1,'COUPON_AMOUNT_REQUIRED','يجب ادخال مبلغ التبرع','Please enter amount');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (11,1,'CREDIT_CARD_TRANSACTION_NUMBER_REQUIRED','يجب ادخال رقم عملية الشراء الخاصة بالكريدت كارد','Please enter credit card transaction number');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (12,1,'ALL_CHEQUE_DETAILS_REQUIRED','يجب ادخال كود البنك ورقم الشيك وتاريخ الشيك','Please enter the bank code,cheque number and cheque date');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (13,1,'MISSING_NEW_PROJECT_INFO','من فضلك قم بإدخال جميع بيانات المشروع','Please enter all project information');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (14,1,'COUNTRY_NOT_EXIST','الدولة غير موجودة','Country doesn''t exist');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (15,1,'PROJECT_TYPE_NOT_EXIST','نوع المشروع غير موجود','Project type doesn''t exist');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (16,1,'PROJECT_STUDY_NOT_EXIST','دراسة المشروع غير موجودة','Project study doesn''t exist');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (17,1,'DONATOR_NOT_EXIST','المتبرع غير موجود','Donator doesn''t exist');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (18,1,'NEW_DONATOR_DETAILS_REQUIRED','من فضلك قم بإدخال بيانات المتبرع الجديد','Please enter new donator details');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (19,1,'MISSING_DONATE_CURRENT_PROJECT_INFO','من فضلك قم باختيار المشروع والمتبرع وادخال مبلغ التبرع','Please select project and donator and enter amount');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (20,1,'OLD_PROJECT_NOT_EXIST','المشروع القديم غير موجود','Old project doesn''t exist');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (21,1,'MISSING_NEW_SPONSORSHIP_INFO','من فضلك قم باختيار االأيتام','Please select orphans');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (22,1,'GIFT_TYPE_NOT_EXIST','نوع الهدية غير موجود','Gift type doesn''t exist');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (23,1,'SPONSOR_NOT_EXIST','الكافل غير موجود','Sponsor doesn''t exist');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (24,1,'DELEGATE_ID_REQUIRED','من فضلك قم بإدخال رقم المفوض','Please enter delegate id');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (25,1,'COUPON_TYPE_ID_REQUIRED','من فضلك قم بإدخال رقم الكوبون','Please enter coupon id');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (26,1,'GIFT_AMOUNT_REQUIRED','من فضلك قم بإدخال مبلغ الهدية','Please enter gift amount');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (27,1,'GIFT_TYPE_ID_REQUIRED','من فضلك قم بإدخال رقم الهدية','Please enter gift id');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (28,1,'ORPHAN_AMOUNT_REQUIRED','من فضلك قم بإدخال مبلغ التبرع لليتيم','Please enter sponsorship amount for orphan');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (29,1,'ORPHAN_ID_REQUIRED','من فضلك قم بإدخال رقم اليتيم','Please enter orphan id');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (30,1,'BANK_CODE_AND_ACCOUNT_NUMBER_REQUIRED','من فضلك قم بإدخال كود البنك ورقم الحساب','Please enter bank code and account number');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (31,1,'MISSING_OLD_SPONSORSHIP_INFO','من فضلك قم باختيار الكافل والأيتام المراد التبرع لهم','Please select sponsor and orphans');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (0,1,'SUCCESS_CODE','تمت العملية نجاح','Success');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (-1,1,'SYSTEM_ERROR_CODE','خطأ غير متوقع','System error');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (3,1,'USER_EXPIRED','انتهت صلاحية المستخدم','User is expired');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (1,1,'WRONG_CREDENTIALS','خطأ فى اسم المستخدم او كلمة المرور','Wrong username or password');
Insert into CAPPS_POS.ERROR_CODE (ID,ACTIVE,ERROR_CODE,ERROR_NAME_ARABIC,ERROR_NAME_ENGLISH) values (2,1,'USER_DISABLED','تم ايقاف المستخدم','User is disabled');
