
  CREATE TABLE "CAPPS"."TM_CHARITY_BOX_TRANSFERS_DTL" 
   (	"TRANSFER_LINE_ID" NUMBER, 
	"CHARITY_BOX_TRANSFER_ID" NUMBER, 
	"TRANSFER_TYPE" NUMBER, 
	"CHARITY_BOX_ID" NUMBER, 
	"NEW_CHARITY_BOX" NUMBER, 
	"SUB_LOCATION_ID" NUMBER, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATION_DATE" DATE, 
	"ACTION_TYPE" NUMBER, 
	"SAFETY_CASE" NUMBER, 
	"FROM_PROTAL" VARCHAR2(1 BYTE), 
	"NOTES" VARCHAR2(2000 BYTE), 
	"STATUS" VARCHAR2(5 BYTE), 
	"SUPERVISOR_ID" NUMBER, 
	"TRANSACTION_NUMBER" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE, 
	 CONSTRAINT "TM_CHARITY_BOX_TRANSFERS_DTLPK" PRIMARY KEY ("TRANSFER_LINE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "TRANSACTION_NUMBER_UNIQUE" UNIQUE ("TRANSACTION_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "TM_CHARITY_BOX_TRANSFERS_D_R01" FOREIGN KEY ("CHARITY_BOX_TRANSFER_ID")
	  REFERENCES "CAPPS"."TM_CHARITY_BOX_TRANSFERS" ("TRANSFER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SBSTBSPACE" ;
