
  CREATE TABLE "CAPPS"."TM_CHARITY_BOXES" 
   (	"CHARITY_BOX_ID" NUMBER, 
	"CHARITY_BOX_NUMBER" VARCHAR2(50 BYTE), 
	"CHARITY_BOX_NAME" VARCHAR2(400 BYTE), 
	"CHARITY_BOX_TYPE" VARCHAR2(100 BYTE), 
	"CHARITY_BOX_PERIOD" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_BY" NUMBER, 
	"LAST_UPDATED_DATE" DATE, 
	"COMMENTS" VARCHAR2(400 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ORG_ID" NUMBER, 
	"STATUS" VARCHAR2(10 BYTE), 
	"SUB_LOCATION_ID" NUMBER, 
	"ASSET_ID" NUMBER, 
	"SUPERVISOR_ID" NUMBER, 
	"EMPLOYEE_CODE" NUMBER, 
	"CATEGORY_OF_BOXES" NUMBER, 
	"CHARITY_BOX_BARCODE" VARCHAR2(100 BYTE), 
	"ONE_DAY_BOX" NUMBER, 
	"SAFETY_CASE" NUMBER, 
	"BRANCH_ID" NUMBER, 
	 CONSTRAINT "TM_CHARITY_BOXES_U01" UNIQUE ("CHARITY_BOX_BARCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "TM_CHARITY_BOXES_U02" UNIQUE ("CHARITY_BOX_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "TM_CHARITY_BOXES_U03" UNIQUE ("CHARITY_BOX_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
