
  CREATE TABLE "CAPPS"."TM_RECEIPTS" 
   (	"RECEIPT_CODE" NUMBER(19,0) NOT NULL ENABLE, 
	"RECEIPT_NUMBER" VARCHAR2(40 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_BY" NUMBER, 
	"TOTAL_AMOUNT" NUMBER(*,0), 
	"TOTAL_PAID" NUMBER(*,0), 
	"REMAINING" NUMBER(*,0), 
	"DONATOR_NAME" NVARCHAR2(100), 
	"DONATOR_PHONE_NO" VARCHAR2(20 BYTE), 
	"COLLECTED" VARCHAR2(1 BYTE), 
	"RECEIPT_DATE" DATE, 
	"ORG_ID" NUMBER, 
	"JV_NO" NUMBER, 
	"BANK_ACCOUNT_ID" VARCHAR2(100 BYTE), 
	"INTERFACED" VARCHAR2(10 BYTE), 
	"COLLECT_DATE" DATE, 
	"COLLECT_NUMBER" VARCHAR2(20 BYTE), 
	"RCPT_SOURCE" CHAR(10 BYTE), 
	"PRINT" NUMBER, 
	"SELECTED" VARCHAR2(10 BYTE), 
	"BATCH_NO" NUMBER, 
	"SLIP_SADKAT" VARCHAR2(100 BYTE), 
	"SLIP_ZAKAT" VARCHAR2(100 BYTE), 
	"ONLINE_BASED" VARCHAR2(1 BYTE), 
	"NO_OF_PRINTS" NUMBER, 
	"COLLECT_ID" NUMBER(9,0), 
	"SUPERVISORS_CODE" NUMBER(19,0), 
	"TM_DELEGATES_CODE" NUMBER(19,0), 
	"CREATEDBY" NUMBER(19,0), 
	"LASTMODIFIEDBY" NUMBER(19,0), 
	"CREATEDON" DATE, 
	"LASTMODIFIEDON" DATE, 
	"LOCATIONCODE" NUMBER(2,0), 
	"SERIALNO" NUMBER(13,0), 
	"COMPANYCODE" NUMBER(19,0), 
	"STATUS" NUMBER(3,0), 
	"NOTES" NVARCHAR2(150), 
	"YEARLYCOMMISSION" NUMBER(1,0), 
	"CONFIRMED" NUMBER, 
	"CREATED_BY" NUMBER, 
	 CONSTRAINT "TM_RECEIPT_PK" PRIMARY KEY ("RECEIPT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE ROW MOVEMENT ;

  CREATE INDEX "CAPPS"."TM_RECEP_DAT_INDX" ON "CAPPS"."TM_RECEIPTS" ("RECEIPT_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "CAPPS"."TM_RECEIPTS_TRG" 
  BEFORE INSERT ON tm_receipts   FOR EACH ROW
DECLARE
L_VALUE NUMBER;
BEGIN
   
   IF :NEW.CREATED_BY IS NULL THEN
      :NEW.CREATED_BY := :NEW.TM_DELEGATES_CODE;
      :NEW.LAST_UPDATE_BY := :NEW.TM_DELEGATES_CODE;
      :NEW.CREATION_DATE  := SYSDATE;
      :NEW.RECEIPT_DATE  := SYSDATE;
      :NEW.LAST_UPDATE_DATE := SYSDATE;
      :NEW.ORG_ID := 1;
      :NEW.TOTAL_PAID := :NEW.TOTAL_AMOUNT;
   ELSE
      :NEW.RECEIPT_DATE  := :NEW.CREATION_DATE;
   END IF;
   
   IF :NEW.STATUS IS NULL THEN
        :NEW.STATUS := 0;
   END IF;           
END;

/
ALTER TRIGGER "CAPPS"."TM_RECEIPTS_TRG" ENABLE;
