package com.ihsan.constants;

public enum ErrorCodeEnum {
	SUCCESS_CODE(0), SYSTEM_ERROR_CODE(-1), WRONG_CREDENTIALS(1), USER_DISABLED(2), USER_EXPIRED(3),
	INVALID_PAYMENT_TYPE(4), DELEGATE_NOT_EXIST(5), RECEIPT_DETAILS_REQUIRED(6), COUPON_TYPE_NOT_EXIST(7),
	COUPON_AMOUNT_LESS_MINIMUM(8), DONATOR_NAME_REQUIRED(9), COUPON_AMOUNT_REQUIRED(10),
	CREDIT_CARD_TRANSACTION_NUMBER_REQUIRED(11), ALL_CHEQUE_DETAILS_REQUIRED(12), MISSING_NEW_PROJECT_INFO(13),
	COUNTRY_NOT_EXIST(14), PROJECT_TYPE_NOT_EXIST(15), PROJECT_STUDY_NOT_EXIST(16), DONATOR_NOT_EXIST(17),
	NEW_DONATOR_DETAILS_REQUIRED(18), MISSING_DONATE_CURRENT_PROJECT_INFO(19), OLD_PROJECT_NOT_EXIST(20),
	MISSING_NEW_SPONSORSHIP_INFO(21), GIFT_TYPE_NOT_EXIST(22), SPONSOR_NOT_EXIST(23), DELEGATE_ID_REQUIRED(24),
	COUPON_TYPE_ID_REQUIRED(25), GIFT_AMOUNT_REQUIRED(26), GIFT_TYPE_ID_REQUIRED(27), ORPHAN_AMOUNT_REQUIRED(28),
	ORPHAN_ID_REQUIRED(29), BANK_CODE_AND_ACCOUNT_NUMBER_REQUIRED(30), MISSING_OLD_SPONSORSHIP_INFO(31),
	FIRST_TITLE_NOT_EXIST(32), ACCESS_DENIED(36), OLD_PASSWORD_WRONG(37);

	private int errorCode;

	public int intValue() {
		return errorCode;
	}

	public String stringValue() {
		return String.valueOf(errorCode);
	}

	private ErrorCodeEnum(int errorCode) {
		this.errorCode = errorCode;
	}
}
