package com.ihsan.constants;

public enum ErrorCodeEnum {
	SUCCESS_CODE(0, "SUCCESS_CODE"), SYSTEM_ERROR_CODE(-1, "SYSTEM_ERROR_CODE"),
	WRONG_CREDENTIALS(1, "WRONG_CREDENTIALS"), USER_DISABLED(2, "USER_DISABLED"), USER_EXPIRED(3, "USER_EXPIRED"),
	INVALID_PAYMENT_TYPE(4, "INVALID_PAYMENT_TYPE"), DELEGATE_NOT_EXIST(5, "DELEGATE_NOT_EXIST"),
	RECEIPT_DETAILS_REQUIRED(6, "RECEIPT_DETAILS_REQUIRED"), COUPON_TYPE_NOT_EXIST(7, "COUPON_TYPE_NOT_EXIST"),
	COUPON_AMOUNT_LESS_MINIMUM(8, "COUPON_AMOUNT_LESS_MINIMUM"),
	DONATOR_NAME_PHONE_REQUIRED(9, "DONATOR_NAME_PHONE_REQUIRED"), COUPON_AMOUNT_REQUIRED(10, "COUPON_AMOUNT_REQUIRED"),
	CREDIT_CARD_TRANSACTION_NUMBER_REQUIRED(11, "CREDIT_CARD_TRANSACTION_NUMBER_REQUIRED"),
	ALL_CHEQUE_DETAILS_REQUIRED(12, "ALL_CHEQUE_DETAILS_REQUIRED"),
	MISSING_NEW_PROJECT_INFO(13, "MISSING_NEW_PROJECT_INFO"), COUNTRY_NOT_EXIST(14, "COUNTRY_NOT_EXIST"),
	PROJECT_TYPE_NOT_EXIST(15, "PROJECT_TYPE_NOT_EXIST"), PROJECT_STUDY_NOT_EXIST(16, "PROJECT_STUDY_NOT_EXIST"),
	DONATOR_NOT_EXIST(17, "DONATOR_NOT_EXIST"), NEW_DONATOR_DETAILS_REQUIRED(18, "NEW_DONATOR_DETAILS_REQUIRED"),
	MISSING_DONATE_CURRENT_PROJECT_INFO(19, "MISSING_DONATE_CURRENT_PROJECT_INFO"),
	OLD_PROJECT_NOT_EXIST(20, "OLD_PROJECT_NOT_EXIST"),
	MISSING_NEW_SPONSORSHIP_INFO(21, "MISSING_NEW_SPONSORSHIP_INFO"), GIFT_TYPE_NOT_EXIST(22, "GIFT_TYPE_NOT_EXIST"),
	SPONSOR_NOT_EXIST(23, "SPONSOR_NOT_EXIST"), DELEGATE_ID_REQUIRED(24, "DELEGATE_ID_REQUIRED"),
	COUPON_TYPE_ID_REQUIRED(25, "COUPON_TYPE_ID_REQUIRED"), GIFT_AMOUNT_REQUIRED(26, "GIFT_AMOUNT_REQUIRED"),
	GIFT_TYPE_ID_REQUIRED(27, "GIFT_TYPE_ID_REQUIRED"), ORPHAN_AMOUNT_REQUIRED(28, "ORPHAN_AMOUNT_REQUIRED"),
	ORPHAN_ID_REQUIRED(29, "ORPHAN_ID_REQUIRED"),
	BANK_CODE_AND_ACCOUNT_NUMBER_REQUIRED(30, "BANK_CODE_AND_ACCOUNT_NUMBER_REQUIRED"),
	MISSING_OLD_SPONSORSHIP_INFO(31, "MISSING_OLD_SPONSORSHIP_INFO"),
	FIRST_TITLE_NOT_EXIST(32, "FIRST_TITLE_NOT_EXIST"), CHARITY_BOX_IN_USE(33, "CHARITY_BOX_IN_USE"),
	CHARITY_BOX_SAME_SOURCE_EXISTS(34, "CHARITY_BOX_SAME_SOURCE_EXISTS"), BARCODE_NOT_EXIST(35, "BARCODE_NOT_EXIST"),
	ACCESS_DENIED(36, "ACCESS_DENIED"), SUBLOCATION_ALREADY_HAS_CHARITYBOX(37, "SUBLOCATION_ALREADY_HAS_CHARITYBOX"),
	NEW_CHARITYBOX_NOT_EXIST_IN_DB(38, "NEW_CHARITYBOX_NOT_EXIST_IN_DB"),
	NEW_CHARITYBOX_MUST_BE_INACTIVE(39, "NEW_CHARITYBOX_MUST_BE_INACTIVE"),
	ONLY_ACTIVE_CHARITYBOX_CAN_BE_COLLECTED(40, "ONLY_ACTIVE_CHARITYBOX_CAN_BE_COLLECTED"),
	CANNOT_REPLACE_CHARITYBOX_WITH_ITSELF(41, "CANNOT_REPLACE_CHARITYBOX_WITH_ITSELF"),
	CANNOT_CHECK_CHARITY_BOX(42, "CANNOT_CHECK_CHARITY_BOX"),
	CHARITYBOX_NOT_EXIST_IN_DB(43, "CHARITYBOX_NOT_EXIST_IN_DB"),
	ONLY_ACTIVE_CHARITYBOX_CAN_BE_REMOVED(44, "ONLY_ACTIVE_CHARITYBOX_CAN_BE_REMOVED"),
	REGION_ALREADY_EXIST(45, "REGION_ALREADY_EXIST"), LOCATION_ALREADY_EXIST(46, "LOCATION_ALREADY_EXIST"),
	SUBLOCATION_ALREADY_EXIST(47, "SUBLOCATION_ALREADY_EXIST"),
	CHARITYBOX_NUMBER_NOT_EXIST(48, "CHARITYBOX_NUMBER_NOT_EXIST"),
	ORPHAN_AMOUNT_OR_GIFT_REQUIRED(49, "ORPHAN_AMOUNT_OR_GIFT_REQUIRED"),
	COUPON_QRCODE_NOT_EXIST(50, "COUPON_QRCODE_NOT_EXIST"), OLD_PASSWORD_WRONG(51, "OLD_PASSWORD_WRONG"),
	CHARITYBOX_MUST_BE_ASSIGNED_TO_SUBLOCATION(52, "CHARITYBOX_MUST_BE_ASSIGNED_TO_SUBLOCATION"),
	WRONG_SAFETY_CASE_BARCODE(53, "WRONG_SAFETY_CASE_BARCODE"), SAFETY_CASE_ACTIVE(54, "SAFETY_CASE_ACTIVE");

	private String errorCode;

	private int errorCodeIntValue;

	public String getErrorCode() {
		return errorCode;
	}

	public int intValue() {
		return errorCodeIntValue;
	}

	private ErrorCodeEnum(int errorCodeIntValue, String errorCode) {
		this.errorCodeIntValue = errorCodeIntValue;
		this.errorCode = errorCode;
	}
}
